version: '3'
services:
    db:
        container_name: cwie-fba-mysql
        image: 'mysql'
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - '3308:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 2022@cwie_fba
            MYSQL_DATABASE: cwie_fba
            MYSQL_USER: cwie_fba
            MYSQL_PASSWORD: 2022@cwie_fba
            MYSQL_ALLOW_EMPTY_PASSWORD: ok
            MYSQL_ROOT_HOST: '%'
        volumes:
            - './data:/var/lib/mysql'
        networks:
            - cwie_fba
    pma:
        container_name: cwie-fba-phpmyadmin
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - 8083:80
        restart: always
        environment:
            PMA_HOST: db
            UPLOAD_LIMIT: 300M
            MYSQL_ROOT_PASSWORD: 'root'
        networks:
            - cwie_fba
        depends_on:
          - db
    api:
        container_name: cwie-fba-api
        build:
            context: .
        restart: always
        ports:
            - '8084:80'
        command: npm run dev
        volumes:
            - '.:/app'
        links:
            - db:db
        networks:
            - cwie_fba
        depends_on:
            - db
networks:
    cwie_fba: 
        driver: bridge
# volumes:
#     db_data:
#         driver: local
